Actions test
Locally the env cannot be solved due to ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/home/imallona/tmp/types.py)

m